feat!: Json view and routes
lenra-io/application-runner pull request #242
Opened 2022-09-20 19:09 UTC by Nesqwik

## Checklist
- [ ] I didn't over-scope my PR
- [ ] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I did not include breaking changes
- [ ] I included unit tests that cover my changes
- [ ] I added/updated the documentation about my changes
- [ ] I made my own code-review before requesting one

## Description of the changes
Major changes in the channel system.
Now, when the client connect to the socket, a new session is created.
When connecting to the socket, the "appName" must be passed using the parameters.

Then the client must join the channel "listeners" and one or many channel "route:*".
The channel "listeners" allow the client tu push the listeners call when a button is pressed.
The channel "route:*" allow the client to get the changes of a certain route.
When joining the channel "route:*", the client must specify the "mode" of the view : "json" or "lenra"

Here an example of a manifest that handle a todo list using the Lenra views AND the json views : 

```javascript
'use strict'
// Widgets

module.exports = async () => {
  return {
    widgets: {
      main: require('./widgets/main'),
      todo: require('./widgets/todo'),
      todos: require('./widgets/todos'),
      menu: require('./widgets/menu'),

      todosJson: require('./widgets/todosJson'),
      todoJson: require('./widgets/todoJson'),
    },
    listeners: {
      new: require('./listeners/new'),
      delete: require('./listeners/delete'),
      toggle: require('./listeners/toggle'),
      onEnvStart: require('./listeners/onEnvStart'),
      onSessionStart: require('./listeners/onSessionStart'),
      onUserFirstJoin: require('./listeners/onUserFirstJoin')
    },
    lenraRoutes: {
      "/": {
        "type": "widget",
        "name": "todos",
        "coll": "todos",
        "query": {
          "user": "@me"
        }
      }
    },
    jsonRoutes: {
      "/todos": {
        "type": "widget",
        "name": "todosJson",
        "coll": "todos",
        "query": {
          "user": "@me",
        }
      },
      "/todos/:todoId": {
        "type": "widget",
        "name": "todoJson",
        "coll": "todos",
        "query": {
          "_id": "@route.todoId"
        }
      }
    }
  }
}
```

You can see the route "/todos" and "/todos/:todoId" in the jsonViews. 
The first one can update the client about the full todo list.
The second one can update the client about a specific todo.

The developper can create any number of routes.

Changes that need to be done : 
- [x] Update the socket/channel system
- [x]  Create a RouteDynSup that will be in change of creating the new routes dynamically
- [x] Create a RouteSupervisor that will be in change to start the RouteServer and the updated ChangeEventManager.
- [x] Update the ChangeEventManager be started once for each route. It will be in change to tell the routes to change if needed.
- [x] Change the UiServer into the RouteServer.
- [x] Update the RouteServer to accept different builder. The LenraBuilder and the JsonBuilder.
- [x] Create the JsonBuilder that will transform the listeners.
- [ ] Update the Context system. New channel ? How to update the views when the context change ? (Probably another PR)

2022-10-05 13:17 UTC, jonas-martinez requested changes

2022-10-05 13:17 UTC, jonas-martinez commented on lib/errors/business_error.ex
> +      {:route_doest_not_exists, "The given route does not exist. Please check your manifest."},
```suggestion
      {:route_does_not_exist, "The given route does not exist. Please check your manifest."},
```

2022-10-05 13:17 UTC, jonas-martinez commented on lib/errors/business_error.ex
> +      {:no_action_in_listener, "Your listener doest not have the required property 'action'"},
```suggestion
      {:no_action_in_listener, "Your listener does not have the required property 'action'"},
```

2022-10-05 13:17 UTC, jonas-martinez commented on lib/channels/app_socket.ex
> +            # Application error
Why did you comment out the error handling code ?

2022-10-05 13:18 UTC, jonas-martinez commented
The code looks good to me but can you provide some informations about how to test this feature ? @Nesqwik

2022-10-06 09:30 UTC, pichoemr requested changes

2022-10-06 09:30 UTC, pichoemr commented on lib/channels/app_socket.ex
> +            :error
According to the Phoenix.Socket hexdoc, connect  can return {:error, term()}, why only return :error instead of a tuple with an error message?
https://hexdocs.pm/phoenix/Phoenix.Socket.html#c:connect/2

2022-10-06 09:30 UTC, pichoemr commented on lib/channels/app_socket.ex
> +        ApplicationRunner.AppSocket.do_create_env_token(env_id)
alias ?

2022-10-06 09:30 UTC, pichoemr commented on lib/session/route_server.ex
> +            "The view mode '#{mode}' is correct. No UI Builder module can be found."
```suggestion
            "The view mode '#{mode}' is incorrect. No UI Builder module can be found."
```

2022-10-13 13:43 UTC, Nesqwik commented on lib/channels/app_socket.ex
> +            # Application error
my mistake, i thought the connect function could only return the :error atom, not a tuple.
It is not the case.
Fixed :)

2022-10-13 13:43 UTC, Nesqwik commented on lib/channels/app_socket.ex
> +            :error
A mistake, fixed :)

2022-10-13 13:49 UTC, Nesqwik commented
> The code looks good to me but can you provide some informations about how to test this feature ? @Nesqwik

Sure ! 
You will need these repo : 
- application_runner, branch json_views
- devtools, branch view-system
  - you might want to update mix.exs to link to your local application_runner : `{:application_runner, path: "../../application-runner"},`
- https://github.com/lenra-io/app_todo_server_example branch main
- https://github.com/lenra-io/app_todo_client_example branch main

Then : 
- In devtools : 
  - `cd server`
  - `mix phx.server`
- In app_todo_server_example, 
  - `npm i`
  - `npm start`
 - In app_todo_client_example, 
   - `npm i`
   - `npm start`

2022-10-14 16:34 UTC, jonas-martinez approved these changes
Looks good to me !

We might need to schedule a meeting with you and @pichoemr to make sure that everything was understood correctly because this is a quite big feature.

2022-10-19 10:07 UTC, pichoemr approved these changes
The change is a bit big, it works and I don't see a problem right now, we can merge.

You will have some conflict with:
Listeners return:
https://github.com/lenra-io/application-runner/pull/264
Listeners return & error return by adapters:
https://github.com/lenra-io/application-runner/pull/262

2022-10-24 13:53 UTC, pichoemr approved these changes

2022-11-01 12:43 UTC, merged

2022-11-01 12:44 UTC, shiipou commented
:tada: This PR is included in version 1.0.0-beta.82 :tada:

The release is available on [GitHub release](https://github.com/lenra-io/application-runner/releases/tag/v1.0.0-beta.82)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-02-27 15:21 UTC, shiipou commented
:tada: This PR is included in version 1.0.0-alpha.1 :tada:

The release is available on [GitHub release](https://github.com/lenra-io/application-runner/releases/tag/v1.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: