feat: Cron Migration
lenra-io/application-runner pull request #252
Opened 2022-10-10 08:11 UTC by jonas-martinez

See Epic https://github.com/lenra-io/Lenra/issues/168

## Checklist
- [ ] I didn't over-scope my PR
- [ ] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I did not include breaking changes
- [ ] I included unit tests that cover my changes
- [ ] I added/updated the documentation about my changes
- [ ] I made my own code-review before requesting one

## Description of the changes

## Technical highlight/advice

2022-10-10 12:03 UTC, pichoemr requested changes

2022-10-10 12:03 UTC, pichoemr commented on priv/repo/migrations/20221007135344_add_cron_table.exs
> +defmodule ApplicationRunner.Repo.Migrations.AddCronTable do
Add a migration

2022-10-11 13:27 UTC, pichoemr approved these changes

2022-10-11 13:36 UTC, shiipou approved these changes

2022-10-11 13:40 UTC, merged

2022-10-11 13:40 UTC, shiipou commented
:tada: This PR is included in version 1.0.0-beta.72 :tada:

The release is available on [GitHub release](https://github.com/lenra-io/application-runner/releases/tag/v1.0.0-beta.72)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-02-27 15:21 UTC, shiipou commented
:tada: This PR is included in version 1.0.0-alpha.1 :tada:

The release is available on [GitHub release](https://github.com/lenra-io/application-runner/releases/tag/v1.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: