feat: add logs
lenra-io/application-runner pull request #297
Opened 2023-01-20 09:37 UTC by pichoemr

#__ 

## Checklist
- [ ] I didn't over-scope my PR
- [ ] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I did not include breaking changes
- [ ] I included unit tests that cover my changes
- [ ] I added/updated the documentation about my changes
- [ ] I made my own code-review before requesting one

## Description of the changes

## Technical highlight/advice

2023-02-10 09:16 UTC, jonas-martinez requested changes

2023-02-10 09:16 UTC, jonas-martinez commented on lib/channels/app_socket.ex
> +          Logger.notice("joined app #{app_name} with params #{inspect(params)}")
```suggestion
          Logger.notice("Joined app #{app_name} with params #{inspect(params)}")
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/channels/route_channel.ex
> +      # Send an error if the ui are malformated
```suggestion
      # Send an error if the ui is malformed
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/environment/dynamic_supervisor.ex
> +      "#{__MODULE__} Start Environment Supervisor with env_metadta: #{inspect(env_metadata)}"
```suggestion
      "#{__MODULE__} Start Environment Supervisor with env_metadata: #{inspect(env_metadata)}"
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/environment/dynamic_supervisor.ex
> +          "#{__MODULE__} failed to start Environment Supervisor with env_metadta: #{inspect(env_metadata)} for reason: #{inspect(reason)}"
```suggestion
          "#{__MODULE__} failed to start Environment Supervisor with env_metadata: #{inspect(env_metadata)} for reason: #{inspect(reason)}"
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/environment/dynamic_supervisor.ex
> +    Logger.debug("Stop Environment for env_id: #{env_id}")
```suggestion
    Logger.debug("Stopping environment for env_id: #{env_id}")
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/environment/dynamic_supervisor.ex
> +        Logger.error("Failed to found Supervision Tree for name: #{inspect(name)}")
```suggestion
        Logger.error("Failed to find supervision tree for name: #{inspect(name)}")
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/environment/dynamic_supervisor.ex
> +        Logger.info("Stop Environment Supervision Tree for name: #{inspect(name)}")
```suggestion
        Logger.info("Stopping environment supervision tree for name: #{inspect(name)}")
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/environment/manifest_handler.ex
> +   Return the Manifest for the given env_id
```suggestion
   Returns the Manifest for the given env_id
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/environment/metadata.ex
> +    The Environmnet metadata.
```suggestion
    The Environment metadata.
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/environment/mongo_instance.ex
> +    Return the config option to start the `Mongo` genserver in the environment supervisor, for the given env_id.
```suggestion
    Returns the config options to start the `Mongo` genserver in the environment supervisor, for the given env_id.
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/environment/query_server.ex
> +    Start monotoring the given ViewServer
```suggestion
    Start monitoring the given ViewServer
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/environment/view_server.ex
> +    Receive notifcation from QueryServer when data changed and we need to refresh view.
```suggestion
    Receive notification from QueryServer when data changed and we need to refresh the view.
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/errors/alert_agent.ex
> +    LenraCommon.Erros.AlertAgent manage Alert & Emergency error
```suggestion
    ApplicationRunner.Errors.AlertAgent manages Alert & Emergency errors
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/errors/alert_agent.ex
> +        # if we send 5 alerts, send an emergency and reset the counter.
```suggestion
        # if we sent 5 alerts, send an emergency and reset the counter.
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/errors/technical_error.ex
> +      {:mongo_error, "Could not access mongo. Please retry later."},
```suggestion
      {:mongo_error, "Could not access mongo. Please try again later."},
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/guardian/app_guardian.ex
> +              "#{__MODULE__} faile to fetch session token for claims: #{inspect(claims)} with error: #{inspect(e)}"
```suggestion
              "#{__MODULE__} failed to fetch session token for claims: #{inspect(claims)} with error: #{inspect(e)}"
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/guardian/app_guardian.ex
> +              "#{__MODULE__} faile to fetch environment token for claims: #{inspect(claims)} with error: #{inspect(e)}"
```suggestion
              "#{__MODULE__} failed to fetch environment token for claims: #{inspect(claims)} with error: #{inspect(e)}"
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/guardian/app_guardian.ex
> +        Logger.error("#{__MODULE__} Unknow token type for claims: #{inspect(claims)}")
```suggestion
        Logger.error("#{__MODULE__} Unknown token type for claims: #{inspect(claims)}")
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/schema/json_shemata.ex
> +    During init we load root component from component_api (root defined in @component_api_directory).
```suggestion
    During init we load the root component from component_api (root defined in @component_api_directory).
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/session/dynamic_supervisor.ex
> +              "#{__MODULE__} DynamicSupervisor cannot found Session for env_id: #{env_id}, session_id: #{session_id}"
```suggestion
              "#{__MODULE__} DynamicSupervisor could not find Session for env_id: #{env_id}, session_id: #{session_id}"
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/session/events/on_session_start.ex
> +        Logger.debug("#{__MODULE__} succesfully run event for session_id: #{session_id}")
```suggestion
        Logger.debug("#{__MODULE__} succesfully ran event for session_id: #{session_id}")
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/session/events/on_user_first_join.ex
> +        "#{__MODULE__} succesfully run event for session_id: #{session_id} and user: #{user_id}"
```suggestion
        "#{__MODULE__} succesfully ran event for session_id: #{session_id} and user: #{user_id}"
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/session/events/on_user_first_join.ex
> +        Logger.debug("#{__MODULE__} user already run onUserFirstJoin for id: #{user_id}")
```suggestion
        Logger.debug("#{__MODULE__} user already ran onUserFirstJoin for id: #{user_id}")
```

2023-02-10 09:16 UTC, jonas-martinez commented on lib/session/ui_builders/lenra_builder.ex
> +              "#{__MODULE__} fail to build children map for session_metadata: #{inspect(session_metadata)} with children: #{inspect(children)} and error: #{inspect(e)}"
```suggestion
              "#{__MODULE__} failed to build children map for session_metadata: #{inspect(session_metadata)} with children: #{inspect(children)} and error: #{inspect(e)}"
```

2023-02-10 14:13 UTC, jonas-martinez requested changes
Can you fix the CI ?

2023-02-14 10:40 UTC, jonas-martinez approved these changes

2023-02-14 10:52 UTC, taorepoara approved these changes

2023-02-14 10:52 UTC, merged

2023-02-14 10:53 UTC, shiipou commented
:tada: This PR is included in version 1.0.0-beta.108 :tada:

The release is available on [GitHub release](https://github.com/lenra-io/application-runner/releases/tag/v1.0.0-beta.108)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-02-27 15:19 UTC, shiipou commented
:tada: This PR is included in version 1.0.0-alpha.1 :tada:

The release is available on [GitHub release](https://github.com/lenra-io/application-runner/releases/tag/v1.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: