feat: some error rework
lenra-io/application-runner pull request #333
Opened 2023-04-24 11:50 UTC by pichoemr

Closes #

## Description of the changes

## Checklist
- [ ] I didn't over-scope my PR
- [ ] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I did not include breaking changes
- [ ] I made my own code-review before requesting one

### I included unit tests that cover my changes
  - [ ] 👍 yes
  - [ ] 🙅 no, because they aren't needed
  - [ ] 🙋 no, because I need help

### I added/updated the documentation about my changes

- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [ ] 📓 docs.lenra.io
- [ ] 🙅 no documentation needed

## Technical highlight/advice

2023-05-15 07:48 UTC, jonas-martinez requested changes

2023-05-15 07:48 UTC, jonas-martinez commented on lib/mongo_storage.ex
> +            {:error, BusinessError.not_an_object_id_tuple()}
```suggestion
            BusinessError.not_an_object_id_tuple()
```

Why do you add `:error` ? It is already present in the call to `BusinessError` thanks to `_tuple()`.

This looks clean like this but if you expand the call to BusinessError to its real value it looks odd.
{:error, {:error, ...}}

2023-05-15 07:48 UTC, jonas-martinez commented on lib/mongo_storage.ex
> +        {:error,
Same thing here and at line 351

2023-05-22 08:15 UTC, pichoemr commented on lib/mongo_storage.ex
> +        {:error, BusinessError.error_during_transaction_start_tuple(%{error_message: msg})}
```suggestion
        BusinessError.error_during_transaction_start_tuple(%{error_message: msg})
```

2023-05-22 08:15 UTC, pichoemr commented on lib/mongo_storage.ex
> +         })}
```suggestion
         BusinessError.error_during_transaction_start_tuple(%{
           error: "uuid already used, please try again"
         })
```

2023-05-22 13:48 UTC, jonas-martinez submitted a review, later dismissed
LGTM

2023-05-22 15:34 UTC, taorepoara approved these changes

2023-05-23 07:35 UTC, merged

2023-05-23 07:35 UTC, shiipou commented
:tada: This PR is included in version 1.0.0-beta.123 :tada:

The release is available on [GitHub release](https://github.com/lenra-io/application-runner/releases/tag/v1.0.0-beta.123)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-05-23 07:36 UTC, shiipou commented
:tada: This PR is included in version 1.0.0-alpha.11 :tada:

The release is available on [GitHub release](https://github.com/lenra-io/application-runner/releases/tag/v1.0.0-alpha.11)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: