fix: ressource route
lenra-io/application-runner pull request #340
Opened 2023-05-17 08:24 UTC by pichoemr

Closes #

## Description of the changes

Replace :ressource to *ressource to accept sub path

## Checklist
- [ ] I didn't over-scope my PR
- [ ] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I did not include breaking changes
- [ ] I made my own code-review before requesting one

### I included unit tests that cover my changes
  - [ ] 👍 yes
  - [ ] 🙅 no, because they aren't needed
  - [ ] 🙋 no, because I need help

https://github.com/lenra-io/server/pull/383

### I added/updated the documentation about my changes

- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [ ] 📓 docs.lenra.io
- [ ] 🙅 no documentation needed

## Technical highlight/advice

2023-05-17 14:53 UTC, taorepoara commented
Can you please add postgres to the docker-compose and document how to use it to run tests in the README as discussed before.

2023-05-19 12:59 UTC, taorepoara requested changes

2023-05-19 12:59 UTC, taorepoara commented on README.md
> +* Install erlang in version 24.2 and elixir in version 1.12.3 otp-24
Isn't the needed elixir version 1.13 ?

2023-05-19 12:59 UTC, taorepoara commented on README.md
> +command at the root of this project or running by hand the docker commands like so :
You should add the docker-compose way to start both databases. Do not remove the basic docker way, but let it in second place.

2023-05-22 08:11 UTC, pichoemr commented on README.md
> +command at the root of this project or running by hand the docker commands like so :
In this project we don't have docker-compose to start both databases but only to start mongo, so I say in the mongo part that we can start it with docker-compose or with commands.

2023-05-22 08:12 UTC, pichoemr commented on README.md
> +* Install erlang in version 24.2 and elixir in version 1.12.3 otp-24
```suggestion
* Install erlang in version 24.2 and elixir in version 1.13 otp-24
```

2023-05-22 13:46 UTC, jonas-martinez approved these changes
LGTM

2023-05-22 15:30 UTC, taorepoara approved these changes

2023-05-22 15:30 UTC, taorepoara commented on README.md
> +* Create the database and start migration `mix setup`. This is equivalent to running the following commands :
`mix setup` does not work. I have this issue: `** (Mix) The task "setup" could not be found`

2023-05-22 15:30 UTC, taorepoara commented on README.md
> +  * `mix run priv/repo/seeds.exs` to fill database with default values
I don't think that there is seeds in this project

2023-05-22 15:30 UTC, taorepoara commented on README.md
> +command at the root of this project or running by hand the docker commands like so :
You should add postres in the docker-compose. It's easier to use

2023-05-22 15:31 UTC, taorepoara commented
Still needs documentation changes but it's not due to this PR so it can be handled later

2023-05-22 15:32 UTC, taorepoara commented on README.md
> +* Create the database and start migration `mix setup`. This is equivalent to running the following commands :
See issue: https://github.com/lenra-io/application-runner/issues/344

2023-05-22 15:33 UTC, taorepoara commented on README.md
> +  * `mix run priv/repo/seeds.exs` to fill database with default values
See https://github.com/lenra-io/application-runner/issues/345

2023-05-22 15:33 UTC, merged

2023-05-22 15:34 UTC, shiipou commented
:tada: This PR is included in version 1.0.0-beta.122 :tada:

The release is available on [GitHub release](https://github.com/lenra-io/application-runner/releases/tag/v1.0.0-beta.122)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-05-23 07:36 UTC, shiipou commented
:tada: This PR is included in version 1.0.0-alpha.11 :tada:

The release is available on [GitHub release](https://github.com/lenra-io/application-runner/releases/tag/v1.0.0-alpha.11)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: