Transaction token
lenra-io/application-runner pull request #342
Opened 2023-05-19 09:28 UTC by pichoemr

Closes https://github.com/lenra-io/application-runner/issues/305

## Description of the changes

## Checklist
- [ ] I didn't over-scope my PR
- [ ] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I did not include breaking changes
- [ ] I made my own code-review before requesting one

### I included unit tests that cover my changes
  - [ ] 👍 yes
  - [ ] 🙅 no, because they aren't needed
  - [ ] 🙋 no, because I need help

### I added/updated the documentation about my changes

- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [ ] 📓 docs.lenra.io
- [ ] 🙅 no documentation needed

## Technical highlight/advice

2023-05-22 15:21 UTC, taorepoara commented on lib/controllers/docs_controller.ex
> +    with filtered_doc <- Map.delete(doc, "_id"),
It seems do be almost the same code. Isn't it better to manage it in the same function ? I don't know the good practices in Elixir ^^

2023-05-22 15:28 UTC, taorepoara approved these changes
Seems good

2023-05-22 15:29 UTC, taorepoara requested changes
A check failed

2023-05-22 15:30 UTC, taorepoara commented
Also the transaction system have to be documented in the docs.lenra.io website

2023-05-30 12:37 UTC, Nesqwik commented on lib/controllers/docs_controller.ex
> +        AppGuardian.encode_and_sign(uuid, %{
We might want to use [Phoenix.Token](https://hexdocs.pm/phoenix/1.6.15/Phoenix.Token.html) for this simple use case.
The goal is to remove Guardian when OAuth will be ready, so we should already start with this feature.
What do you think @taorepoara ?

2023-05-30 12:37 UTC, Nesqwik reviewed
One comment about Guardian...

2023-05-30 13:24 UTC, taorepoara commented
@pichoemr Can you see that ?

2023-05-30 14:29 UTC, pichoemr commented on lib/controllers/docs_controller.ex
> +        AppGuardian.encode_and_sign(uuid, %{
Is Phoenix.token compatible with guardian?
The API is under Guardian Plug so if we change the token here and guardian isn't compatible, we won't be able to access the API with the transaction token.
We're going to remove Guardian from the server with the OAuth system, but keep AppGuardian?

2023-05-31 07:25 UTC, taorepoara commented
We will remove guardian later to be sure of the impacts. This PR does not have to handle that.

2023-06-05 10:14 UTC, taorepoara submitted a review, later dismissed
Seems OK

2023-06-05 15:22 UTC, Nesqwik commented on config/config.exs
> +  level: :none
We might want to keep default to Warning

2023-06-05 15:22 UTC, Nesqwik commented on lib/webhooks/webhook_services.ex
>          ApplicationServices.run_listener(
Any reason why the webooks are calling the Listener directly instead of using `EventHandler.send_env_event/4` ?
If not, we should use it and remove the Token creation/deletion here.

2023-06-05 15:22 UTC, Nesqwik commented on lib/event_handler.ex
> +    TokenAgent.revoke_token(env_id, uuid)
Ok I'm not sure about this.
The big issue i can see is that if run_listener fail and raise an error, we will have a memory leak.
The token in TokenAgent will never be removed unless the environment stop.

To prevent this, be SURE that this is the only part of the code where token are added/removed. and then, add something like that : 
```elixir
def handle_call(...) do
# Create token, run listener
after
TokenAgent.revoke_token(...)
end
```

2023-06-06 14:08 UTC, pichoemr commented on config/config.exs
> +  level: :none
It was for my personal test, I forgot to cancel the change.

2023-08-31 10:07 UTC, taorepoara requested changes
I'll test it locally but seems ok (except for the log config)

2023-08-31 10:07 UTC, taorepoara commented on config/config.exs
> +  level: :none
@pichoemr Don't forget it

2023-09-08 06:40 UTC, Nesqwik submitted a review, later dismissed
I'm not 100% sure about this one, but it seems ok.
We should keep an eye on this feature to ensure everything is ok in production.
Since we are a bit in a rush, i'm approving this anyway.

2023-09-08 09:02 UTC, taorepoara approved these changes

2023-09-08 09:03 UTC, merged