fix: Add content-length header for app requests
lenra-io/application-runner pull request #353
Opened 2023-07-20 18:46 UTC by taorepoara

Closes #

## Description of the changes

## Checklist
- [ ] I didn't over-scope my PR
- [ ] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I did not include breaking changes
- [ ] I made my own code-review before requesting one

### I included unit tests that cover my changes
  - [ ] 👍 yes
  - [ ] 🙅 no, because they aren't needed
  - [ ] 🙋 no, because I need help

### I added/updated the documentation about my changes

- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [ ] 📓 docs.lenra.io
- [ ] 🙅 no documentation needed

## Technical highlight/advice

2023-07-21 09:48 UTC, jonas-martinez approved these changes

2023-07-21 10:05 UTC, jonas-martinez requested changes
Tests are not working

2023-07-21 13:28 UTC, taorepoara commented
The tests are also broken on the beta branch, but my changes seems that my changes added one test failure. I have fixed the previous one, but I don't understand how to fix the last one...
@Nesqwik can you help me with this ?

2023-07-31 07:36 UTC, Nesqwik approved these changes

2023-07-31 08:00 UTC, jonas-martinez approved these changes

2023-07-31 08:00 UTC, merged

2023-07-31 08:01 UTC, shiipou commented
:tada: This PR is included in version 1.0.0-beta.126 :tada:

The release is available on [GitHub release](https://github.com/lenra-io/application-runner/releases/tag/v1.0.0-beta.126)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: